# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pagina_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_uno(object):
    def setupUi(self, Ventana_uno):
        Ventana_uno.setObjectName("Ventana_uno")
        Ventana_uno.resize(350, 415)
        Ventana_uno.setMinimumSize(QtCore.QSize(350, 415))
        Ventana_uno.setMaximumSize(QtCore.QSize(350, 415))
        Ventana_uno.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.verticalLayoutWidget = QtWidgets.QWidget(Ventana_uno)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_one = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_one.setContentsMargins(40, 40, 40, 5)
        self.lay_ver_one.setSpacing(15)
        self.lay_ver_one.setObjectName("lay_ver_one")
        self.lbl_CocaCola_imagen = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_CocaCola_imagen.setStyleSheet("border-image: url(:/cct/Coca_Cola_logo_white.png);")
        self.lbl_CocaCola_imagen.setText("")
        self.lbl_CocaCola_imagen.setObjectName("lbl_CocaCola_imagen")
        self.lay_ver_one.addWidget(self.lbl_CocaCola_imagen)
        self.lbl_bienvenida = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_bienvenida.setStyleSheet("\n"
"font: 75 italic 15pt \"MS Sans Serif\";\n"
"\n"
"color: rgb(255, 255, 255);")
        self.lbl_bienvenida.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_bienvenida.setObjectName("lbl_bienvenida")
        self.lay_ver_one.addWidget(self.lbl_bienvenida)
        self.lbl_ingresarNombre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_ingresarNombre.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Tw Cen MT Condensed Extra Bold\";")
        self.lbl_ingresarNombre.setObjectName("lbl_ingresarNombre")
        self.lay_ver_one.addWidget(self.lbl_ingresarNombre)
        self.txt_nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_nombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 87 8pt \"Arial Black\";")
        self.txt_nombre.setInputMask("")
        self.txt_nombre.setText("")
        self.txt_nombre.setObjectName("txt_nombre")
        self.lay_ver_one.addWidget(self.txt_nombre)
        self.btn_ingresar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_ingresar.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 0, 0);\n"
"")
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.lay_ver_one.addWidget(self.btn_ingresar)
        self.lay_ver_one.setStretch(0, 2)
        self.lay_ver_one.setStretch(1, 1)
        self.lay_ver_one.setStretch(2, 1)
        self.lay_ver_one.setStretch(3, 1)
        self.lay_ver_one.setStretch(4, 2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Ventana_uno)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 330, 351, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.lay_ver_two = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.lay_ver_two.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_two.setObjectName("lay_ver_two")
        self.lbl_copyright = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_copyright.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 11pt \"Monotype Corsiva\";")
        self.lbl_copyright.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_copyright.setObjectName("lbl_copyright")
        self.lay_ver_two.addWidget(self.lbl_copyright)

        self.retranslateUi(Ventana_uno)
        QtCore.QMetaObject.connectSlotsByName(Ventana_uno)

    def retranslateUi(self, Ventana_uno):
        _translate = QtCore.QCoreApplication.translate
        Ventana_uno.setWindowTitle(_translate("Ventana_uno", "Bienvenido"))
        self.lbl_bienvenida.setText(_translate("Ventana_uno", "Sistema de control vacacional"))
        self.lbl_ingresarNombre.setText(_translate("Ventana_uno", "inserte su nombre:"))
        self.btn_ingresar.setText(_translate("Ventana_uno", "ingresar"))
        self.lbl_copyright.setText(_translate("Ventana_uno", "2017 The Coca Cola company"))
from imagenes import Coca_cola_logo_rc
