# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TerminosYCondiciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Terminos_y_condiciones(object):
    def setupUi(self, Terminos_y_condiciones):
        Terminos_y_condiciones.setObjectName("Terminos_y_condiciones")
        Terminos_y_condiciones.resize(620, 421)
        Terminos_y_condiciones.setMinimumSize(QtCore.QSize(620, 421))
        Terminos_y_condiciones.setMaximumSize(QtCore.QSize(620, 421))
        self.verticalLayoutWidget = QtWidgets.QWidget(Terminos_y_condiciones)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 621, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(20, 20, 20, 20)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_terminosYCondiciones = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_terminosYCondiciones.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";")
        self.lbl_terminosYCondiciones.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_terminosYCondiciones.setObjectName("lbl_terminosYCondiciones")
        self.lay_ver_principal.addWidget(self.lbl_terminosYCondiciones)
        self.txt_terminos_y_condiciones = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.txt_terminos_y_condiciones.setReadOnly(True)
        self.txt_terminos_y_condiciones.setObjectName("txt_terminos_y_condiciones")
        self.lay_ver_principal.addWidget(self.txt_terminos_y_condiciones)
        self.chk_Aceptar = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chk_Aceptar.setObjectName("chk_Aceptar")
        self.lay_ver_principal.addWidget(self.chk_Aceptar)
        self.lay_hor_botones = QtWidgets.QHBoxLayout()
        self.lay_hor_botones.setObjectName("lay_hor_botones")
        self.btn_acepto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_acepto.setEnabled(False)
        self.btn_acepto.setObjectName("btn_acepto")
        self.lay_hor_botones.addWidget(self.btn_acepto)
        self.btn_noAcepto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_noAcepto.setObjectName("btn_noAcepto")
        self.lay_hor_botones.addWidget(self.btn_noAcepto)
        self.lbl_logo_coca_cola = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_logo_coca_cola.setStyleSheet("border-image: url(:/cct2/Coca_cola_logo_rojo.png);")
        self.lbl_logo_coca_cola.setText("")
        self.lbl_logo_coca_cola.setObjectName("lbl_logo_coca_cola")
        self.lay_hor_botones.addWidget(self.lbl_logo_coca_cola)
        self.lay_hor_botones.setStretch(0, 1)
        self.lay_hor_botones.setStretch(1, 1)
        self.lay_hor_botones.setStretch(2, 2)
        self.lay_ver_principal.addLayout(self.lay_hor_botones)
        self.lay_ver_principal.setStretch(0, 1)
        self.lay_ver_principal.setStretch(1, 5)
        self.lay_ver_principal.setStretch(2, 1)
        self.lay_ver_principal.setStretch(3, 2)

        self.retranslateUi(Terminos_y_condiciones)
        QtCore.QMetaObject.connectSlotsByName(Terminos_y_condiciones)

    def retranslateUi(self, Terminos_y_condiciones):
        _translate = QtCore.QCoreApplication.translate
        Terminos_y_condiciones.setWindowTitle(_translate("Terminos_y_condiciones", "Terminos y condiciones"))
        self.lbl_terminosYCondiciones.setText(_translate("Terminos_y_condiciones", "TERMINOS Y CONDICIONES"))
        self.txt_terminos_y_condiciones.setPlainText(_translate("Terminos_y_condiciones", "\n"
"          TERMINOS Y CONDICIONES\n"
"\n"
"            A.  PROHIBIDA SU VENTA O DISTRIBUCIÓN SIN AUTORIZACIÓN.\n"
"            B.  PROHIBIDA LA ALTERACIÓN DEL CÓDIGO FUENTE O DISEÑO DE LAS INTERFACES GRÁFICAS.\n"
"            C.  NO SOY RESPONSABLE DEL MAL USO DE ESTE SOFTWARE.\n"
"\n"
"          LOS ACUERDOS LEGALES EXPUESTOS ACONTINUACIÓN RIGEN EL USO QUE USTED HAGA DE ESTE SOFTWARE\n"
"          NO SE RESPONSABILIZAN DEL USO QUE USTED\n"
"          HAGA CON ESTE SOFTWARE Y SUS SERVICIOS. PARA ACEPTAR ESTOS TERMINOS HAGA CLIC EN (ACEPTO)\n"
"          SI USTED NO ACEPTA ESTOS TERMINOS, HAGA CLIC EN (NO ACEPTO) Y NO UTILICE ESTE SOFTWARE.\n"
"\n"
"          PARA MAYOR INFORMACIÓN SOBRE NUESTROS PRODUCTOS O SERVICIOS, POR FAVOR VISITE\n"
"          http://www.pagina.com"))
        self.chk_Aceptar.setText(_translate("Terminos_y_condiciones", "Yo andres acepto"))
        self.btn_acepto.setText(_translate("Terminos_y_condiciones", "Continuar"))
        self.btn_noAcepto.setText(_translate("Terminos_y_condiciones", "No acepto"))
from imagenes import Coca_cola_logo_rojo_rc
